### ISSUE TITLE
Sequelize.sync() error

### ISSUE THREAD

**Issue by Noah-Huppert** [SquadUp/SquadUp-Server#2]
The error 

```
Unhandled rejection SequelizeDatabaseError: syntax error at or near "false"
    at Query.formatError (/home/noah/Documents/SquadUp-Server/node_modules/sequelize/lib/dialects/postgres/query.js:437:14)
    at null.<anonymous> (/home/noah/Documents/SquadUp-Server/node_modules/sequelize/lib/dialects/postgres/query.js:112:19)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Query.handleError (/home/noah/Documents/SquadUp-Server/node_modules/pg/lib/query.js:108:8)
    at null.<anonymous> (/home/noah/Documents/SquadUp-Server/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/home/noah/Documents/SquadUp-Server/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

is thrown when you add the statement

```
sequelize.sync()
```

This statement is supposed to enforce the defined schema onto the database. So something is going wrong in the business logic.

**Comment by Noah-Huppert** [comment]
Turns out you have to put the `timestamps: false` option in a separate config object after the schema obj.
